import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon3.ico" />
      </Head>
        <div className={styles.logo}>
        <Image
          src="/Logo3.png"
          alt="Moray Logo"
          width={200}
          height={50}
          priority
          />
        </div>
      <div className={styles.container}>
        <div className={styles.card}>
        <Image className={styles.card_image}
          src="/No_image.png"
          alt="No image"
          width={160}
          height={160}
          priority
          />
          <p className={styles.title}>トラウツボ</p>
          <p className={styles.description}>Leopard moray eel</p>
          <p className={styles.description}>体長:約1.2m</p>
        </div>
        <div className={styles.card2}>
        <Image className={styles.card_image}
          src="/No_image.png"
          alt="No image"
          width={220}
          height={220}
          priority
          />
          <p className={styles.title}>トラウツボ</p>
          <p className={styles.description}>Leopard moray eel</p>
          <p className={styles.description}>体長:約1.2m</p>
        </div>
      </div>
    </>
  )
}
